spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: localhost:9092 # 指定kafka地址，可以多个
    producer:
      retries: 0
    consumer:
      group-id: test-consumer-group # 指定默认消费者group id
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 5000ms